# Generated by Django 5.1.6 on 2025-03-04 12:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'polls',
                'indexes': [models.Index(fields=['created_at'], name='polls_created_7a9936_idx'), models.Index(fields=['expires_at'], name='polls_expires_8d776f_idx'), models.Index(fields=['is_active'], name='polls_is_acti_fab1e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.poll')),
            ],
            options={
                'db_table': 'poll_options',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voter_id', models.CharField(max_length=255)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.option')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.poll')),
            ],
            options={
                'db_table': 'votes',
            },
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['poll'], name='poll_option_poll_id_756716_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['option'], name='votes_option__7be548_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['voter_id'], name='votes_voter_i_706843_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['voted_at'], name='votes_voted_a_e5bf4b_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['poll', 'voter_id'], name='votes_poll_id_6a4af4_idx'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('voter_id', 'poll'), name='unique_voter_per_poll'),
        ),
    ]
