# Generated by Django 5.1.6 on 2025-03-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_voter_per_poll',
        ),
    ]
