# Generated by Django 5.1.6 on 2025-03-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_vote_unique_voter_per_poll'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vote',
            name='votes_voter_i_706843_idx',
        ),
        migrations.RemoveIndex(
            model_name='vote',
            name='votes_poll_id_6a4af4_idx',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voter_id',
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['poll'], name='votes_poll_id_13d8f7_idx'),
        ),
    ]
