# Generated by Django 5.1.6 on 2025-03-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_vote_votes_voter_i_706843_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vote',
            name='votes_poll_id_13d8f7_idx',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='poll',
        ),
        migrations.AddField(
            model_name='vote',
            name='voter_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['voter_id'], name='votes_voter_i_706843_idx'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('voter_id', 'option'), name='unique_voter_per_option'),
        ),
    ]
